### ISSUE TITLE
更可靠的「取得文章標題」方法

### ISSUE THREAD

**Issue by eight04** [Truth0906/PTTLibrary#13]
目前的文章標題是由文章前幾行提出，但事實上 PTT 的文章標題是可以被移動，甚至刪除的。例︰
https://www.ptt.cc/bbs/asciiart/M.1529136658.A.F58.html

一個比較可靠的方法是在文章列表按大 T，就可以看到完整的文章標題︰
![image](https://user-images.githubusercontent.com/1324510/41558030-31dc032e-7372-11e8-9498-77536377aaa5.png)
但這只對自己發的文有用。

另一個方法是按 ^x 轉錄、或按 y 回覆該文章︰
![image](https://user-images.githubusercontent.com/1324510/41558285-e35b9b78-7372-11e8-8215-af1631226f71.png)
![image](https://user-images.githubusercontent.com/1324510/41558303-f316d140-7372-11e8-91ee-81a69f1ac2fc.png)
但是標題會因為前面增加了 `Re: ` 或 `Fw: ` 而少了 4 個字元。

還有一個方法︰1) 先以大 F 把文章轉到信箱，並進入信箱（若要擷取的文章本來就在信箱裡，可省略這步驟）。2) 在文章前按小 x，把信轉給自己。此時就會顯示完整標題︰
![image](https://user-images.githubusercontent.com/1324510/41558510-9f88811c-7373-11e8-955e-1b55e293c3ff.png)

**Comment by Truth0906** [comment]
這可能會導致過慢，近期我會實作，但會保留兩種取得標題的方式。

**Comment by eight04** [comment]
這個方法是真的很慢，取得標題的時間比取得文章的時間還長。
