### ISSUE TITLE
原始資料中應處理移位碼

### ISSUE THREAD

**Issue by eight04** [Truth0906/PTTLibrary#14]
![image](https://user-images.githubusercontent.com/1324510/41558882-e8683192-7374-11e8-915e-86b697c2d9e5.png)
![image](https://user-images.githubusercontent.com/1324510/41558919-0d69efa8-7375-11e8-8e8b-018d0bd0c904.png)
![image](https://user-images.githubusercontent.com/1324510/41558934-1a8bbb26-7375-11e8-8a32-05188abe117a.png)

使用的是這篇︰
文章代碼(AID): #1R6Im2l1 (C_Chat) [ptt.cc] [ANSI] 偶像大師 MILLION LIVE 
文章網址: https://www.ptt.cc/bbs/C_Chat/M.1528376322.A.BC1.html

**Comment by Truth0906** [comment]
我看了一下，這些是從 PTT 接到的耶...

**Comment by eight04** [comment]
抱歉，標題不夠清楚。我想表達的是「移位碼並未被處理」。在不處理移位碼的情況下，文章內容甚至會整個遺失（非 rawData）。例如這篇文章︰
#1RA8BG7g (Test) [ptt.cc] [測試]                          
https://www.ptt.cc/bbs/Test/M.1529381584.A.1EA.html

執行以下程式抓取文章內容
```python
from pprint import pprint
from PTTLibrary import PTT

bot = PTT.Library(kickOtherLogin=False)
bot.login(USER, PASSWORD)
err, post = bot.getPost("test", "1RA8BG7g")
pprint((
	post.getBoard(),
	post.getID(),
	post.getAuthor(),
	post.getContent()
))
```
可以看到兩行文字都消失了︰
```
[06-19 12:25:26][資訊] 偵測到前景執行使用編碼: utf-8
[06-19 12:25:26][資訊] 使用者帳號:
[06-19 12:25:26][資訊] 密碼:
[06-19 12:25:26][資訊] 產生 SSH 金鑰完成
[06-19 12:25:26][資訊] 連線頻道 0 啟動
[06-19 12:25:36][資訊] 頻道 0 建立互動通道成功
[06-19 12:25:36][資訊] 頻道 0 輸入帳號
[06-19 12:25:36][資訊] 頻道 0 輸入密碼
[06-19 12:25:36][資訊] 頻道 0 讀取 PTT 畫面..
[06-19 12:25:37][資訊] 不刪除重複登入的連線
[06-19 12:25:39][資訊] 任意鍵繼續
[06-19 12:25:39][資訊] 頻道 0 登入成功
('test',
 '1RA8BG7g',
 'eight0 (人類)',
 '--▉▏                                      '
 '▉▏                                       '
 '▊▎                                     '
 'e▆e  \u3000
    '
 'e      e                                   \n'
 '\n'
 '--')

```

**Comment by Truth0906** [comment]
好，沒問題。
