### ISSUE TITLE
遇到寬度 > 80 的文章不要自動換行

### ISSUE THREAD

**Issue by eight04** [Truth0906/PTTLibrary#16]
範例︰
文章代碼(AID): #1QxJjbqT (asciiart) [ptt.cc] [ANSI] 龍貓
文章網址: https://www.ptt.cc/bbs/asciiart/M.1525496677.A.D1D.html

這是用 PTTLibrary 抓下來的︰
[66. [asciiart] [ANSI] 龍貓 [CAMIYA (CAMIYA)] (20180505130434).zip](https://github.com/Truth0906/PTTLibrary/files/2112869/66.asciiart.ANSI.CAMIYA.CAMIYA.20180505130434.zip)

我希望能有一個選項可以選擇不要自動換行，保持每行完整。

P.S. 若想在網頁版看大圖，可以加以下的 CSS 讓內容不要自動換行︰
```css
#main-content {
  white-space: pre;
}
```

**Comment by Truth0906** [comment]
目前為了文章推文即時性，並沒有從網頁抓文章喔@@ 都是直接登入 PTT 解析的。

**Comment by eight04** [comment]
我並不是希望從網頁上抓文章，而是希望有選項把「自動斷行的文字」接回（？）一行。

**Comment by Truth0906** [comment]
那怎麼知道...那是自動斷行?

**Comment by eight04** [comment]
我不太確定 PTTLibrary 是怎麼爬的，所以列出大概可行的方案，這篇為例︰
文章代碼(AID): #1R9_jKGC (Test) [ptt.cc] [測試] 123456789012345678901234 
文章網址: https://www.ptt.cc/bbs/Test/M.1529346900.A.40C.html            

1. 按小 j 一行一行爬。假如畫面上的第一行被自動斷行，按下 j 會一次跳過兩行以上。

    * 捲到第 12 行
      ![image](https://user-images.githubusercontent.com/1324510/41578911-2c6251a0-73c7-11e8-971b-5bdc2784ab9e.png)
    * 按 j，會一次跳過兩行
      ![image](https://user-images.githubusercontent.com/1324510/41578945-50424418-73c7-11e8-80f2-6e01169501cd.png)
    * 然後藉由偵測有幾行被跳過，判斷哪幾行是連在一起的。
    * 缺點︰
      - 如果每行都長一樣，就很難偵測有幾行被跳過。
      - 如果某行長到佔滿一整面，按小 j 會直接跳過一整頁，看不到行尾。
        
2. 顯示斷行符號，輸入 `om`，然後檢查行尾是否是斷行符號
    ![image](https://user-images.githubusercontent.com/1324510/41579064-e1bd74e4-73c7-11e8-89c0-86ef72152a5b.png)
    缺點︰
      - 如果遇到假的斷行符號（自行在行尾加一個亮白色的 `\`），會判斷錯誤
      - 如果某行長到佔滿一整面，按小 j 會直接跳過一整頁，看不到行尾。

3. 顯示斷行符號，並且直接截行 `owm`
    ![image](https://user-images.githubusercontent.com/1324510/41579265-ca1d9dae-73c8-11e8-8438-770252707741.png)
    * 偵測到截行符號時，輸入 `>` 將畫面往右移，取得被截的文字。
    * 整行都取得後（偵測不到截行符號後），輸入對應數量的 `<` 移回原位。
    * 優點︰
      - 沒有前述方法的缺點
      - 即使有假的截行符號，也會在右移後發現該符號是假的，為使用者文章的一部份。
