### ISSUE TITLE
開放等待時間為可自行設定

### ISSUE THREAD

**Issue by GniN** [Truth0906/PTTLibrary#17]
我從國外使用ptt，連線的時間會比在台灣長很多，
使用預設的等待時間會不斷的出現timeout而無法使用，
我更改以下幾個數值後即可正常使用，請問是否能開放以下幾個參數為可設定呢?

(PTT.py line: 253 - 256)
```
PreWait = 0.01
EveryWait = 0.05
MaxEveryWait = 0.1 
```

若作者大大允許，我可以發PR

**Comment by Truth0906** [comment]
沒問題

**Comment by Truth0906** [comment]
已經整合好囉!!!
