### ISSUE TITLE
支援PEP8

### ISSUE THREAD

**Issue by kaltu** [Truth0906/PTTLibrary#26]
是否有考慮向PEP8規範靠攏？
使用此library的時候一直有PEP8 violation warning
程式碼風格也不pythonic

**Comment by Truth0906** [comment]
https://www.python.org/dev/peps/pep-0008/
Note

**Comment by Truth0906** [comment]
預計在 0.8 實現

**Comment by Truth0906** [comment]
最新一版的程式碼，已經推上 github 囉，看看還有沒有問題 :D
