### ISSUE TITLE
支援 i18n

### ISSUE THREAD

**Issue by theoneisneo** [Truth0906/PTTLibrary#27]
1.ptt.py檔案有點長 有無考慮重構一下?
2.雖然PTT主要使用中文 但有些時候可能會在僅支援英文的電腦上執行BOT 這時候錯誤訊息需要是英文的比較方便.
有修改的意願嗎?
或著我找時間幫你改?

**Comment by Truth0906** [comment]
我們可以合作:D

**Comment by Truth0906** [comment]
已經開了分支，Dev_0.8

**Comment by theoneisneo** [comment]
> 我們可以合作:D

OK. 我最近在忙, 有空就先改一些東西.

**Comment by Truth0906** [comment]
No problem

**Comment by theoneisneo** [comment]
雖然還是有點忙但應該可以開始投入了.
先討論一下支援多種語系的實作方法.
我想到的是增加一個print_ptt_msg()的function or class
依照設定的值(語系)去讀對應的字串後印出.
關於這樣做, 你有什麼看法嗎?

**Comment by Truth0906** [comment]
沒問題。
可參考
https://github.com/danhper/python-i18n

**Comment by Truth0906** [comment]
嗨，今天有寫了一個架構，在 1.0 裡面了

**Comment by Truth0906** [comment]
我寫好囉!!!最近會推上 pypi

**Comment by theoneisneo** [comment]
阿靠我都忘記我有答應要協作QQ. 太忙了. Sorry~

**Comment by Truth0906** [comment]
我還以為你看到我的程式碼太醜就崩潰了，哈哈哈哈哈哈

**Comment by theoneisneo** [comment]
XDDDDD. 沒有這種事. 如果覺得寫得不漂亮但有用的東西更應該一起討論弄好一點.
話說我之前喵到有個
def __WaterBallProceeor(self):

        if self.__WaterBallHandler == None:
            return

        while len(self.__WaterBallList) != 0:
            CurrentWaterBall = self.__WaterBallList.pop(0)

好像作法改成別的了.
不過還是提一下.
1. 原則上不會用長度是否非0來判斷一個list是否還有用,
while self.__WaterBallList:
應該就可以.

2.
原則上list不使用pop(0).
因為pop()的時間複雜度是O(1), 而pop(0)的時間複雜度是O(n). n是list的長度.
pop(0)的時候會把後面的元素都搬到前面來.
如果需要pop(0), 會用deque取代list. 由於底層資料結構設計的不同. 時間複雜度也是O(1).

**Comment by Truth0906** [comment]
又學到了，謝謝耶，我再多看看這之類的用法
