### ISSUE TITLE
當登入者信箱超過上限時不會提示

### ISSUE THREAD

**Issue by tentenlee100** [Truth0906/PTTLibrary#3]
如果登入的使用者他的個人信件炸掉的時候
畫面不會有任何提示
就變成他會一直重新登入，無限迴圈
看是否遇到這種狀況的時候就跳提示，並終止無限迴圈的問題。

**Comment by Truth0906** [comment]
OK，我會盡快修正此問題。

**Comment by Truth0906** [comment]
@tentenlee100 
嗨 最新的 0.5.1版本已經修正此問題囉!!! 你更新看看!
