### ISSUE TITLE
當讀文章遇到 [ 文字不足 ] 等... 時直接崩潰

### ISSUE THREAD

**Issue by al957826402** [Truth0906/PTTLibrary#33]
當我用
ErrCode, Post = PTTBot.getPost(Board=Board, PostIndex=index)時
如果那篇文章是文字不足、不符合XX版等...
程式會直接崩潰登出， 目前我實在找不到避免得方法
懇請作者指點 謝謝。

**Comment by Truth0906** [comment]
可以給我哪個板 跟文章代碼嗎?

**Comment by al957826402** [comment]
movie版 index = 153602 文字不足

**Comment by Truth0906** [comment]
看起來OK，請問你是指
https://www.ptt.cc/bbs/movie/M.1553926632.A.FF8.html
這一篇文嗎?

**Comment by al957826402** [comment]
不是耶 抱歉因為手邊沒有電腦
例如movie 3/31的一篇文章
特定族群挑釁引戰<x111222333>
這種被管理員刪除類型的文章

**Comment by Truth0906** [comment]
你可以列舉一下你現在使用的版本嗎?

**Comment by Truth0906** [comment]
我試了一下，你說的文可以重現。
已經排入修復清單中。

**Comment by Truth0906** [comment]
已經修正囉。
