### ISSUE TITLE
爬隱版文章

### ISSUE THREAD

**Issue by rjjq** [Truth0906/PTTLibrary#35]
PTTLibrary   0.8.7版 會因為無法得到文章的連結會出現問題

**Comment by Truth0906** [comment]
0.8.8 更新囉!!!試試看 :D

**Comment by rjjq** [comment]
1. 隱版的文章不會有帶文章網址，於PTT.py 614行會出錯
2. PTT.py 1036行 : index = self._ConnectCore.send(Cmd, TargetList)
    若找尋的結果不滿一頁的時候會出錯，這個index的檢查目的為何？

**Comment by Truth0906** [comment]
能否給我一個例子，好讓我重現一下?

**Comment by Truth0906** [comment]
更新囉!!!試試看:D

**Comment by rjjq** [comment]
> 更新囉!!!試試看:D

收到~已經正常了!!

**Comment by Truth0906** [comment]
感動
