### ISSUE TITLE
查詢無名片用戶 ParseError

### ISSUE THREAD

**Issue by tsoliangwu0130** [Truth0906/PTTLibrary#36]
若使用者沒有名片，則在[這行](https://github.com/Truth0906/PTTLibrary/blob/5c61546c806f5815f8de3a102c5b62ba5eff13c1/PTTLibrary/PTT.py#L1624)中的 `Data` string list 長度則會有 11 行 （第 11 行為：`<user> 目前沒有名片`），進而觸發 `Exceptions.ParseError(OriScreen)` 導致使用者資料擷取失敗。

**Comment by tsoliangwu0130** [comment]
I can create a PR to help to fix it if you want. Just let me know what's your thought on it 😄

**Comment by Truth0906** [comment]
Roger that

**Comment by Truth0906** [comment]
0.8.8 更新囉!!!試試看 :D

**Comment by tsoliangwu0130** [comment]
Sweet! Issue fixed. Thanks for the quick work!
