### ISSUE TITLE
支援 SSH 連線

### ISSUE THREAD

**Issue by jmlntw** [Truth0906/PTTLibrary#4]
希望能支援使用 SSH 連線到 PTT 的功能。
（之前看到 https://github.com/liuyenting/pttparser 就是用 `paramiko` 連 SSH 登入 PTT。）

**Comment by Truth0906** [comment]
謝謝您的建議，這會放在優先處理的事項中。

**Comment by Truth0906** [comment]
@jmlntw 已經開了 SupportSSH branch 
可隨時關注

**Comment by Truth0906** [comment]
全新主線已經支援 SSH囉!!!每次連線會更換連線的金鑰! 試試看感覺怎麼樣
