### ISSUE TITLE
無法正確取得推文

### ISSUE THREAD

**Issue by bigtongue5566** [Truth0906/PTTLibrary#41]
PushAuthorPattern有誤只會取得12字元ID的推文

**Comment by Truth0906** [comment]
你好 可以給我範例文章嗎？

**Comment by bigtongue5566** [comment]
https://www.ptt.cc/bbs/Stock/M.1567125002.A.57C.html
https://i.imgur.com/bMjFzhl.png

**Comment by Truth0906** [comment]
馬上幫你處理一下

**Comment by Truth0906** [comment]
已經於 0.8.12 修正
