### ISSUE TITLE
取得大範圍文章會卡住

### ISSUE THREAD

**Issue by bigtongue5566** [Truth0906/PTTLibrary#43]
程式碼
```
Board='Stock'
SearchType=PTT.PostSearchType.Keyword
Condition='盤中閒聊'
TestRange = 100
NewestIndex = PTTBot.getNewestIndex(
    PTT.IndexType.Board,
    Board,
    SearchType=SearchType,
    SearchCondition=Condition,
)
StartIndex = NewestIndex - TestRange + 1
print(f'預備爬行 {Board} 編號 {StartIndex} ~ {NewestIndex} 文章')
ErrorPostList, DelPostList = PTTBot.crawlBoard(
    crawlHandler,
    Board,
    StartIndex=StartIndex,
    EndIndex=NewestIndex,
    SearchType=SearchType,
    SearchCondition=Condition,
)
```
![debug](https://i.imgur.com/Fqm2U7n.png)

**Comment by Truth0906** [comment]
好，我看一下情況

**Comment by Truth0906** [comment]
解掉了。

原因是我用來判斷文章結束的標的是
`PostEnd = [
        '瀏覽',
        '頁 (100%)',
        '回應'
    ]`

但這篇文章結尾，不知道為什麼沒有"回應"，改成偵測離開後就可以跑完所有測試案例了

![image](https://user-images.githubusercontent.com/16451441/64246150-daf63000-cf3e-11e9-961e-940d92a0cb5e.png)

此解法將會在 0.8.13 更新

**Comment by Truth0906** [comment]
更新囉！試試看

**Comment by bigtongue5566** [comment]
有試過沒有問題了 謝謝大大

**Comment by Truth0906** [comment]
👍

**Comment by bigtongue5566** [comment]
> 解掉了。
> 
> 原因是我用來判斷文章結束的標的是
> `PostEnd = [ '瀏覽', '頁 (100%)', '回應' ]`
> 
> 但這篇文章結尾，不知道為什麼沒有"回應"，改成偵測離開後就可以跑完所有測試案例了
> 
> ![image](https://user-images.githubusercontent.com/16451441/64246150-daf63000-cf3e-11e9-961e-940d92a0cb5e.png)
> 
> 此解法將會在 0.8.13 更新

後來仔細看了一下好像是頁數超過100頁造成回應會被省略掉
下面是例子:
  瀏覽 第 103/103 頁 (100%)  目前顯示: 第 2232~2254 行      (h)說明 (←/q)離開 
  瀏覽 第 54/54 頁 (100%)  目前顯示: 第 1166~1188 行 (y)回應(X/%)推文 (←)離開

**Comment by Truth0906** [comment]
原來是這樣子，一開始開發真的很難測到這個 XDD
感謝你的回覆:D
