### ISSUE TITLE
server rejected WebSocket connection: HTTP 403

### ISSUE THREAD

**Issue by buck5060** [Truth0906/PTTLibrary#44]
## 描述
 - 當嘗試與Ptt建立連線時，發生WebSocket 403 Error

## Log
- https://pastebin.com/u1PzHyvQ

## 可能解法
- 嘗試將 ConnectCore.py:191 改成 `origin='https://term.ptt.cc'`，可以正常連線

**Comment by Truth0906** [comment]
已經更新，感恩。
