### ISSUE TITLE
server rejected WebSocket connection: HTTP 403

### ISSUE THREAD

**Issue by pahome** [Truth0906/PTTLibrary#46]
PTTLibrary ver: 0.8.25
Platform: Windows10

今天嘗試了很多次都是同個錯誤碼，請問要怎麼解決ptt擋了websocket連線的問題呢?

是這周才開始遇到這問題的，在別台電腦上測試也是一樣的error codes

也想問一下造成403的原因是什麼

謝謝

**Comment by Truth0906** [comment]
您好，批踢踢更改了 origin 限制，請更新至最新 0.8.26 😄

**Comment by pahome** [comment]
好的 謝謝
可以請教下ptt的origin是什麼意思嗎 謝謝

**Comment by Truth0906** [comment]
批踢踢主機有限制連線的來源網址，連線前我們需要在以下程式碼修改來源。

https://github.com/Truth0906/PTTLibrary/blob/515239ca8272b2e21518c7489653a867162c610b/PTTLibrary/ConnectCore.py#L191

修改成正確的網址就可以正確連線了。
