### ISSUE TITLE
想要有丟水球功能

### ISSUE THREAD

**Issue by vi000246** [Truth0906/PTTLibrary#6]
你好 這是我寫的PTT爬蟲
丟水球在第156行
https://github.com/vi000246/PTTOnlineTracker/blob/master/PTT.py

想問能不能將這個功能整合到PTTLibrary裡呢

**Comment by Truth0906** [comment]
沒問題!!

**Comment by Truth0906** [comment]
目前全新版本在 SupportSSH branch 實作中

**Comment by Truth0906** [comment]
全新主線已經推出囉!!!多了丟水球功能以外，也新增接水球功能喔!!!可以試試看
