### ISSUE TITLE
無法取得使用者登入次數

### ISSUE THREAD

**Issue by vi000246** [Truth0906/PTTLibrary#7]
程式碼:
https://github.com/vi000246/PttArmyRadar/blob/master/PTT.py

我用UserInfo.getLoginTime()回傳的結果都是1
想問這是程式bug嗎

**Comment by Truth0906** [comment]
應該是BUG 我會排入全新架構的測試範例

**Comment by Truth0906** [comment]
昨天整進全新主線，可以再試試看嘛?

**Comment by Truth0906** [comment]
我仔細看了一下，你的程式碼好像不太對。
你可以參考 https://github.com/Truth0906/PTTLibrary/blob/master/Test.py

> ErrCode, UserInfo = PTTBot.getUser(IDs)
        if ErrCode == PTT.ErrorCode.NoUser:
            PTTBot.Log('沒有此使用者')
            continue
        elif ErrCode != PTT.ErrorCode.Success:
            PTTBot.Log('getUserInfo fail error code: ' + str(ErrCode))
            continue
        
        PTTBot.Log('使用者ID: ' + UserInfo.getID())
        PTTBot.Log('使用者經濟狀況: ' + str(UserInfo.getMoney()))
        PTTBot.Log('登入次數: ' + str(UserInfo.getLoginTime()))
        PTTBot.Log('有效文章數: ' + str(UserInfo.getLegalPost()))
        PTTBot.Log('退文文章數: ' + str(UserInfo.getIllegalPost()))
        PTTBot.Log('目前動態: ' + UserInfo.getState() + '!')
        PTTBot.Log('信箱狀態: ' + UserInfo.getMail() + '!')
        PTTBot.Log('最後登入時間: ' + UserInfo.getLastLogin() + '!')
        PTTBot.Log('上次故鄉: ' + UserInfo.getLastIP() + '!')
        PTTBot.Log('五子棋戰績: ' + str(UserInfo.getFiveChess()[0]) + ' 勝 ' + str(UserInfo.getFiveChess()[1]) + ' 敗 ' + str(UserInfo.getFiveChess()[2]) + ' 和')
        PTTBot.Log('象棋戰績:' + str(UserInfo.getChess()[0]) + ' 勝 ' + str(UserInfo.getChess()[1]) + ' 敗 ' + str(UserInfo.getChess()[2]) + ' 和')

**Comment by vi000246** [comment]
好的 謝謝你
