### ISSUE TITLE
最近發文遇到的問題

### ISSUE THREAD

**Issue by tentenlee100** [Truth0906/PTTLibrary#9]
最近發文，系統不再是說發文成功，而是顯示以下字串
`順利貼出佈告，本篇文章不列入記錄，敬請包涵`
但是程式沒判斷到這段，導致顯示失敗。

**Comment by Truth0906** [comment]
是在Test 版發文的嗎?

**Comment by Truth0906** [comment]
嗨 目前 0.6.2 版本還會有這個問題嗎? 如無回應，三天後關閉此issue。
